### ISSUE TITLE
Meals for Facebook Hackathon 2014

### ISSUE THREAD

**Issue by pirroh** [HackEPFL/events#4]
Let's open a new issue to track the progress :)

|  Date |  Meal | People | Cost | Delivery | Payment | Status |
| --- | --- | --- | --: | --- | --- | --- |
| **Sat** lunch | Pizzas | 90 | ?? | 1:00pm | Credit Card | Done |
| **Sat** evening | Chinese | 85+10 | CHF ~2400.- | 8:00pm | Credit Card | Done |
| **Sun** morning | Croissants | ?? | ?? | 8:00am | ?? | ?? |
| **Sun** lunch | Thai | ?? | ?? | 1:00pm | ?? | ?? |
| **W-E** | Drinks | 80 | ?? |  |  | ?? |
|  |  | **Total** | **??** |  |  |  |

**Comment by romac** [comment]
So, here's the table I put together last year:

|  Date |  Meal | People | Final cost | Status | Delivery | Payment |
| --- | --- | --- | --: | --- | --- | --- |
| **Saturday** lunch | Pizzas | 60 | CHF 936.00 |  | 1:00pm | Credit card |
| **Saturday** evening | Chinese | 50 | CHF 1355.00 |  | 8:00pm | Credit card |
| **Sunday** morning | Croissants | 50 | CHF 195.00 |  | 8:00am | Bill |
| **Sunday** lunch | Thai | 50 | CHF 1200.00 |  | 1:00pm | Credit card at shop |
| **Whole weekend** | Drinks | 50 | CHF 500.00 |  |  |  |
|  |  | **Total** | **CHF 4206.-** |  |  |  |

Note that prices may vary this year but I guess the number above provide a good approximation.

I recall that we've had lots of leftovers for Sunday's lunch. I hereby suggest we order pizzas instead of Thai food.

Also, do you remember which meal your preferred (Chinese or Thai)? If we only order one kind of meal, as suggested above, let's order whichever was the tastiest.

So, here's how it went last time for Saturday's evening (**[China Domicile](http://chinadomicile.ch/)**):

> CHF 25.50 per person.
> Delivery around 7pm.
> We can call them Thursday or Friday morning to tell them the exact number of meals we need.
> We can pay with a credit card when they come to get their stuff back.
> They'll deliver "bain-maries", and, for an additional CHF 60-80.-, they can also bring plates, forks, etc.
> I still have to send them an e-mail with the address of delivery + map, as well as the name to put on the > invoice.

For Sunday's lunch (**[Saveur d'Ailleurs](http://www.saveursdailleurs.ch/)**, Thai):

> CHF 24.00 per person.
> Delivery around 12pm.
> We can call them Friday morning to tell them the exact number of meals we need.
> They'll also deliver "bain-maries" or something like that, along with paper plates, and biodegradable forks/knives.
> **There's one issue: we can't pay them by credit card on delivery.** But
> a) They can make an invoice, and we (Ruth) will pay them by bank transfer (if that's an option for Ruth).
> b) We can go to the restaurant and pay there with a credit card. But the restaurant is located at Ouchy…

And for Sunday's breakfast (**[Fleur de Pains](http://www.fleurdepains.ch/)**):

> Called Fleur de Pains for Sunday morning breakfast, and they can deliver croissants + chocolate breads(?). 
> Should cost us 250.- or something like that, will ask for an estimation today.
> **Fleur de Pains doesn't accept payment by credit card at all** (neither on delivery nor at the shop itself), so the only way to pay them is via invoice.

Saturday's lunch is pretty straightforward. We call them the day before, and we pay with a credit card on delivery.

**Comment by dtsbourg** [comment]
As discussed with @pirroh yesterday, I think we should stick to the original plan and just tune the amount of food we get depending on the amount of people. Also have the leftovers from sunday's lunch get picked up a little later in the afternoon instead of right after lunch so people can always snack later on. 

All ok with that so @romac and I can start calling ?

**Comment by romac** [comment]
@pirroh @FredericJacobs: Does anyone remember how many people actually showed up last year? Might help us extrapolate how many people will likely come this year given that we have ~ the same number of attendees.  

## 

Romain Ruetschi

http://romac.me

**Comment by pirroh** [comment]
Around 3/4AM I counted > 40 people, and during the initial talk it was ~55/60.
I also remember there has been a spike with the registrations few hours before the deadline, so I guess we can already expect more people than last year :)

**Comment by dtsbourg** [comment]
The guy from Fleur de Pains is on vacation this week, he'll be back monday but it shouldn't be a problem.

I talked to the thai roulotte they aren't available but she said she would ask some friends of hers and call me back towards 8PM with a proposal.

**Comment by romac** [comment]
Alright, just called China Domicile and ordered 70 regular menus (same as last year, described below) + 10 vegetarian meals (_nouilles sautées au légumes_). The guy will send me an offer before Sunday, and we can call him back next week to adapt the final number, settle the invoice + delivery.

**Menu A** - Fr. 27.50 / person
- Rouleau de printemps (1 pièce)
- Salade chinoise
- Poulet à la sauce aigre-douce
- Porc aigre-piquant
- Bœuf aux légumes
- Riz parfumé
- Salade de fruits chinois

I'll update the table above to reflect the costs once I've got the offer.

EDIT: 70, not 80.

**Comment by romac** [comment]
Just sent a preview of the newsletter to hackers@epfl.ch. Please tell me if you spot a typo, or have any modifications.

**Comment by FredericJacobs** [comment]
Me gusta.

**Comment by dtsbourg** [comment]
Looks great !

**Comment by dtsbourg** [comment]
Just got off the phone with the thai girl. She couldn't give me a fixed price, she has to check with her coworker but she said it should ok. An estimate would 20-25 CHF/pp, and the dishes I order were : 
- Green curry beef with thai basil, aubergines and zucchini
- Yellow curry chicken with potatoes and peanuts
- Red curry pork with bamboo shoots and veggies
- Noodles with veggies and shrimp on the side ( so we have a vegetarian option )
- Servings of rice on the side

They would come with dishes (disposable) and cutlery, and bain-maries if the Chinese guys take theirs back earlier. I order for 70-90 people, we can confirm the exact numbers a couple days before. 

We can adjust the dishes if you think that's too much curry, those were just the ones i thought of off the top of my hat.

**Comment by dtsbourg** [comment]
They just got back to me and are ok to work on the sunday, but for 25 chf/pp for 70 people, 24chf/pp for 90 people. Please get back to me as soon as possible to know if that is ok with you so I can confirm with her.

**Comment by pirroh** [comment]
The prices are aligned with last year, so I would say no problem at all.
We might get the final confirmation from FB on Mon/Tue, but for now let's go on like this!

P.S.: we need to decide when we go to do shopping for the drinks/snacks

**Comment by dtsbourg** [comment]
Update : 
Have confirmed for the thai people. We will tell them the exact amount of people on thursday.

I'm having trouble getting through to fleur de pains, i've called almost 10 times, one answer from a girl who said I should take to the manager, but no answer from him all day. If someone wants to try, please do I can dm the number. 

Edit : [19:20] The guy doesn't answer ... 
Edit 2 : [21:39] Still no answer ... Will try tomorrow
Edit 3 : [10:36] Tried 3 more times this morning impossible to get a hold of this guy

**Comment by dtsbourg** [comment]
Finally got through to Fleur de pains, we have an order in for sunday at 8 AM for (as of now, probably subject to change) for 70 pains au chocolat and 20 croissants
